<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\User;
use Illuminate\Database\Seeder;

class ExerciseSeeder extends Seeder
{
    public function run(): void
    {
        $active = false;
        $exercises = [
            ['name' => '90 degree handstand push up', 'active' => $active],
            ['name' => '90 degree pike push up', 'active' => $active],
            ['name' => '90 degree push up', 'active' => $active],
            ['name' => 'Abdominal crunch', 'active' => $active],
            ['name' => 'Ab wheel rollout', 'active' => $active],
            ['name' => 'Archer dips', 'active' => $active],
            ['name' => 'Archer push up', 'active' => $active],
            ['name' => 'Archer squat', 'active' => $active],
            ['name' => 'Arnold press', 'active' => $active],
            ['name' => 'Arm extended plank', 'active' => $active],
            ['name' => 'Arms high partial sit up', 'active' => $active],
            ['name' => 'Back lever', 'active' => $active],
            ['name' => 'Ball push up', 'active' => $active],
            ['name' => 'Barbell bench press', 'active' => $active],
            ['name' => 'Barbell hip thrust', 'active' => $active],
            ['name' => 'Barbell rollout', 'active' => $active],
            ['name' => 'Barbell row', 'active' => $active],
            ['name' => 'Barbell squat', 'active' => $active],
            ['name' => 'Barbell upright row', 'active' => $active],
            ['name' => 'Barrel roll plank', 'active' => $active],
            ['name' => 'Bench leg raises', 'active' => $active],
            ['name' => 'Bent over row', 'active' => $active],
            ['name' => 'Bicep bar curl', 'active' => $active],
            ['name' => 'Bicycle crunches', 'active' => $active],
            ['name' => 'Biking', 'active' => $active],
            ['name' => 'Bird dog', 'active' => $active],
            ['name' => 'Body rows', 'active' => $active],
            ['name' => 'Body weight row', 'active' => $active],
            ['name' => 'Box jump', 'active' => $active],
            ['name' => 'Box squat', 'active' => $active],
            ['name' => 'Bulgarian split squat', 'active' => $active],
            ['name' => 'Burpees', 'active' => $active],
            ['name' => 'Butt kicks', 'active' => $active],
            ['name' => 'Butterfly hold', 'active' => $active],
            ['name' => 'Cable crunch', 'active' => $active],
            ['name' => 'Cable lateral raise', 'active' => $active],
            ['name' => 'Cable pull through', 'active' => $active],
            ['name' => 'Cable rope overhead triceps extension', 'active' => $active],
            ['name' => 'Cable row', 'active' => $active],
            ['name' => 'Cable standing hip abduction', 'active' => $active],
            ['name' => 'Cable triceps push down', 'active' => $active],
            ['name' => 'Cable woodchopper', 'active' => $active],
            ['name' => 'Calf stretch', 'active' => $active],
            ['name' => 'Cat cow stretch', 'active' => $active],
            ['name' => 'Chest stretch', 'active' => $active],
            ['name' => 'Chin up', 'active' => $active],
            ['name' => 'Circular plank', 'active' => $active],
            ['name' => 'Clapping push up', 'active' => $active],
            ['name' => 'Close grip push up', 'active' => $active],
            ['name' => 'Cobra stretch', 'active' => $active],
            ['name' => 'Cross body shoulder stretch', 'active' => $active],
            ['name' => 'Crunch', 'active' => $active],
            ['name' => 'Crunch hold', 'active' => $active],
            ['name' => 'Curl up', 'active' => $active],
            ['name' => 'Deadlift', 'active' => $active],
            ['name' => 'Decline barbell bench press', 'active' => $active],
            ['name' => 'Decline crunch', 'active' => $active],
            ['name' => 'Decline dumbbell bench press', 'active' => $active],
            ['name' => 'Deep Lunge', 'active' => $active],
            ['name' => 'Deep push up', 'active' => $active],
            ['name' => 'Diamond push up', 'active' => $active],
            ['name' => 'Dips', 'active' => $active],
            ['name' => 'Dive bomber push up', 'active' => $active],
            ['name' => 'Downward dog knee tuck', 'active' => $active],
            ['name' => 'Dumbbell bicep curls', 'active' => $active],
            ['name' => 'Dumbbell front raise', 'active' => $active],
            ['name' => 'Dumbbell lateral raise', 'active' => $active],
            ['name' => 'Dumbbell pullover', 'active' => $active],
            ['name' => 'Dumbbell row', 'active' => $active],
            ['name' => 'Dumbbell shoulder press', 'active' => $active],
            ['name' => 'Dumbbell squat', 'active' => $active],
            ['name' => 'Dumbbell step up', 'active' => $active],
            ['name' => 'Easy walk', 'active' => $active],
            ['name' => 'Elbow plank', 'active' => $active],
            ['name' => 'Elevated Pike hold', 'active' => $active],
            ['name' => 'Elevated pike push up', 'active' => $active],
            ['name' => 'Explosive chin up', 'active' => $active],
            ['name' => 'Explosive dip', 'active' => $active],
            ['name' => 'Explosive knee push up', 'active' => $active],
            ['name' => 'Explosive push up', 'active' => $active],
            ['name' => 'Face pulls', 'active' => $active],
            ['name' => 'Feet up crunch', 'active' => $active],
            ['name' => 'Fingertips push up', 'active' => $active],
            ['name' => 'Fire hydrant', 'active' => $active],
            ['name' => 'Flat bench barbell press', 'active' => $active],
            ['name' => 'Flat bench dumbbell press', 'active' => $active],
            ['name' => 'Flutter kicks', 'active' => $active],
            ['name' => 'Free handstand push up', 'active' => $active],
            ['name' => 'Frog stand', 'active' => $active],
            ['name' => 'Front lever', 'active' => $active],
            ['name' => 'Front Lever knee raise', 'active' => $active],
            ['name' => 'Front lever raise', 'active' => $active],
            ['name' => 'Front lever raise to bar', 'active' => $active],
            ['name' => 'Front squat', 'active' => $active],
            ['name' => 'Full planche push up', 'active' => $active],
            ['name' => 'Glute bridge', 'active' => $active],
            ['name' => 'Goblet squat', 'active' => $active],
            ['name' => 'Ground donkey kicks', 'active' => $active],
            ['name' => 'Hamstring stretch', 'active' => $active],
            ['name' => 'Hand Plank push up', 'active' => $active],
            ['name' => 'Hand release push up', 'active' => $active],
            ['name' => 'Handstand', 'active' => $active],
            ['name' => 'Handstand against wall', 'active' => $active],
            ['name' => 'Handstand dismount', 'active' => $active],
            ['name' => 'Handstand kick up', 'active' => $active],
            ['name' => 'Handstand push up', 'active' => $active],
            ['name' => 'Hanging leg raise', 'active' => $active],
            ['name' => 'Hanging knee raise', 'active' => $active],
            ['name' => 'Hefesto', 'active' => $active],
            ['name' => 'High crunch', 'active' => $active],
            ['name' => 'High knees', 'active' => $active],
            ['name' => 'High plank', 'active' => $active],
            ['name' => 'High-to-low crossover', 'active' => $active],
            ['name' => 'Hollow body hold', 'active' => $active],
            ['name' => 'Horizontal jump', 'active' => $active],
            ['name' => 'Human flag', 'active' => $active],
            ['name' => 'Incline barbell bench press', 'active' => $active],
            ['name' => 'Incline bench cable fly', 'active' => $active],
            ['name' => 'Incline dumbbell bench press', 'active' => $active],
            ['name' => 'incline dumbbell chest press', 'active' => $active],
            ['name' => 'Inclined push up', 'active' => $active],
            ['name' => 'Inverted wrist push up', 'active' => $active],
            ['name' => 'Jackknife sit up', 'active' => $active],
            ['name' => 'Jump squat', 'active' => $active],
            ['name' => 'Jumping lunge', 'active' => $active],
            ['name' => 'Jumping jack', 'active' => $active],
            ['name' => 'Jumping rope', 'active' => $active],
            ['name' => 'Knee hug', 'active' => $active],
            ['name' => 'Knee push up', 'active' => $active],
            ['name' => 'Knee to elbow push up', 'active' => $active],
            ['name' => 'Knee to chest', 'active' => $active],
            ['name' => 'Kneeling cable crunch', 'active' => $active],
            ['name' => 'Lateral leg raise', 'active' => $active],
            ['name' => 'Lateral lunge', 'active' => $active],
            ['name' => 'Lateral walk plank', 'active' => $active],
            ['name' => 'Leg press', 'active' => $active],
            ['name' => 'Legs raise hold', 'active' => $active],
            ['name' => 'Legs raise', 'active' => $active],
            ['name' => 'Legs raise negative', 'active' => $active],
            ['name' => 'Legs scissors', 'active' => $active],
            ['name' => 'Lunge', 'active' => $active],
            ['name' => 'Lying hip raises', 'active' => $active],
            ['name' => 'Lying leg raise', 'active' => $active],
            ['name' => 'Maltese push up', 'active' => $active],
            ['name' => 'Medicine ball seated knee tuck', 'active' => $active],
            ['name' => 'Mountain climbers', 'active' => $active],
            ['name' => 'Muscle up', 'active' => $active],
            ['name' => 'Neck stretch', 'active' => $active],
            ['name' => 'Negative push up', 'active' => $active],
            ['name' => 'Neutral grip push up', 'active' => $active],
            ['name' => 'Oblique crunch', 'active' => $active],
            ['name' => 'Oblique leg raise', 'active' => $active],
            ['name' => 'One arm body row', 'active' => $active],
            ['name' => 'One arm cable lateral raise', 'active' => $active],
            ['name' => 'One arm handstand', 'active' => $active],
            ['name' => 'One arm pull up', 'active' => $active],
            ['name' => 'One arm push up', 'active' => $active],
            ['name' => 'One leg cable kickback', 'active' => $active],
            ['name' => 'Overhead triceps extension', 'active' => $active],
            ['name' => 'Pelican push up', 'active' => $active],
            ['name' => 'Pike push up', 'active' => $active],
            ['name' => 'Pistol squat', 'active' => $active],
            ['name' => 'Planche lean push up', 'active' => $active],
            ['name' => 'Planche push up', 'active' => $active],
            ['name' => 'Plank leg raise', 'active' => $active],
            ['name' => 'Plank jack', 'active' => $active],
            ['name' => 'Plank jumps', 'active' => $active],
            ['name' => 'Plank knee to elbow', 'active' => $active],
            ['name' => 'Plank rolls', 'active' => $active],
            ['name' => 'Plank toe taps', 'active' => $active],
            ['name' => 'Plank walk', 'active' => $active],
            ['name' => 'Power walk', 'active' => $active],
            ['name' => 'Pseudo push up', 'active' => $active],
            ['name' => 'Pull up', 'active' => $active],
            ['name' => 'Pull up with bands', 'active' => $active],
            ['name' => 'Pulse squat', 'active' => $active],
            ['name' => 'Push up', 'active' => $active],
            ['name' => 'Resistance band push up', 'active' => $active],
            ['name' => 'Reverse crunch', 'active' => $active],
            ['name' => 'Reverse grip barbell row', 'active' => $active],
            ['name' => 'Reverse grip lat pull down', 'active' => $active],
            ['name' => 'Ring push up', 'active' => $active],
            ['name' => 'Running', 'active' => $active],
            ['name' => 'Russian leans', 'active' => $active],
            ['name' => 'Russian twist', 'active' => $active],
            ['name' => 'Scapular push up', 'active' => $active],
            ['name' => 'Scissors', 'active' => $active],
            ['name' => 'Seated chest press machine', 'active' => $active],
            ['name' => 'Seated dumbbell Arnold press', 'active' => $active],
            ['name' => 'Seated side-straddle stretch', 'active' => $active],
            ['name' => 'Shotgun row', 'active' => $active],
            ['name' => 'Shoulder stretch', 'active' => $active],
            ['name' => 'Shrimp squat', 'active' => $active],
            ['name' => 'Side crunch', 'active' => $active],
            ['name' => 'Side plank', 'active' => $active],
            ['name' => 'Side Plank Raise', 'active' => $active],
            ['name' => 'Side plank star hold', 'active' => $active],
            ['name' => 'Side stretch', 'active' => $active],
            ['name' => 'Side to side push up', 'active' => $active],
            ['name' => 'Single arm lat pull down', 'active' => $active],
            ['name' => 'Single bar push up', 'active' => $active],
            ['name' => 'Single leg deadlift', 'active' => $active],
            ['name' => 'Single leg drops', 'active' => $active],
            ['name' => 'Single leg glute bridge', 'active' => $active],
            ['name' => 'Single leg push up', 'active' => $active],
            ['name' => 'Sit up', 'active' => $active],
            ['name' => 'Sitting punches', 'active' => $active],
            ['name' => 'Skin the cat', 'active' => $active],
            ['name' => 'Skull crushers', 'active' => $active],
            ['name' => 'Slow dip', 'active' => $active],
            ['name' => 'Slow motion push up', 'active' => $active],
            ['name' => 'Sphinx push up', 'active' => $active],
            ['name' => 'Spider curls', 'active' => $active],
            ['name' => 'Spiderman plank', 'active' => $active],
            ['name' => 'Spiderman push up', 'active' => $active],
            ['name' => 'Squat', 'active' => $active],
            ['name' => 'Stair jump', 'active' => $active],
            ['name' => 'Standing calf raise', 'active' => $active],
            ['name' => 'Standing quadriceps stretch', 'active' => $active],
            ['name' => 'Star plank', 'active' => $active],
            ['name' => 'Step ups', 'active' => $active],
            ['name' => 'Straddle planche push up', 'active' => $active],
            ['name' => 'Straight arm pull down', 'active' => $active],
            ['name' => 'Straight bar dips', 'active' => $active],
            ['name' => 'Stretch legs', 'active' => $active],
            ['name' => 'Sumo squat', 'active' => $active],
            ['name' => 'Superman hold', 'active' => $active],
            ['name' => 'Superman plank', 'active' => $active],
            ['name' => 'Supinated push up', 'active' => $active],
            ['name' => 'Supine spinal twist', 'active' => $active],
            ['name' => 'Switching ball push up', 'active' => $active],
            ['name' => 'Switching push up', 'active' => $active],
            ['name' => 'Tiger bend push up', 'active' => $active],
            ['name' => 'Toe to bar', 'active' => $active],
            ['name' => 'Toe touch', 'active' => $active],
            ['name' => 'Triceps extension', 'active' => $active],
            ['name' => 'Tuck crunch', 'active' => $active],
            ['name' => 'Tuck planche push up', 'active' => $active],
            ['name' => 'Twisted crunch', 'active' => $active],
            ['name' => 'Typewriter push up', 'active' => $active],
            ['name' => 'Uneven push up', 'active' => $active],
            ['name' => 'V bar pulldown', 'active' => $active],
            ['name' => 'V crunch', 'active' => $active],
            ['name' => 'V sit hold', 'active' => $active],
            ['name' => 'V sit up', 'active' => $active],
            ['name' => 'V-ups', 'active' => $active],
            ['name' => 'Walk', 'active' => $active],
            ['name' => 'Walking lunge', 'active' => $active],
            ['name' => 'Wall push up', 'active' => $active],
            ['name' => 'Wall sit', 'active' => $active],
            ['name' => 'Wall squat', 'active' => $active],
            ['name' => 'Weighted push up', 'active' => $active],
            ['name' => 'Weighted russian twist', 'active' => $active],
            ['name' => 'Wide arms push up', 'active' => $active],
            ['name' => 'Wide grip cable row', 'active' => $active],
            ['name' => 'Wide grip pull up', 'active' => $active],
            ['name' => 'Windshield wipers', 'active' => $active],
            ['name' => 'Wrist stretch', 'active' => $active],
        ];

        $system = User::where("email", 'system@system.com')->first();
        foreach ($exercises as $data) {
            $exercise = new Exercise($data);
            $exercise->createdBy()->associate($system);
            $exercise->updatedBy()->associate($system);
            $exercise->save();
        }
    }
}
